# -*- coding: utf-8 -*-
"""self-pruning-neural-network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCZ2Rn9nLxjYrlwDad9ceH1ROrhyk6xY
"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

!pip install torch torchvision matplotlib

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features))

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return torch.matmul(x, pruned_weights.t()) + self.bias

    def get_gates(self):
        return torch.sigmoid(self.gate_scores)

class PrunableNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(32*32*3, 128)
        self.fc2 = PrunableLinear(128, 64)
        self.fc3 = PrunableLinear(64, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def get_all_gates(self):
        return torch.cat([
            self.fc1.get_gates().view(-1),
            self.fc2.get_gates().view(-1),
            self.fc3.get_gates().view(-1)
        ])

transform = transforms.Compose([
    transforms.ToTensor(),
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

# Reduce dataset size for speed
trainset = torch.utils.data.Subset(trainset, range(5000))

trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)

testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

def train_model(lambda_sparse):
    model = PrunableNet().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    epochs = 2   # fast training

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for images, labels in trainloader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            classification_loss = criterion(outputs, labels)

            gates = model.get_all_gates()
            sparsity_loss = torch.sum(gates)

            loss = classification_loss + lambda_sparse * sparsity_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Lambda {lambda_sparse} | Epoch {epoch+1} | Loss: {total_loss:.4f}")

    return model

def evaluate(model):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in testloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total

    gates = model.get_all_gates()
    sparsity = (gates < 1e-2).sum().item() / gates.numel() * 100

    return accuracy, sparsity, gates.detach().cpu().numpy()

lambdas = [0.001, 0.01, 0.1]
results = []

for lam in lambdas:
    print(f"\nTraining with lambda = {lam}")
    model = train_model(lam)

    acc, sparsity, gates = evaluate(model)
    results.append((lam, acc, sparsity))

    print(f"Lambda: {lam} | Accuracy: {acc:.2f}% | Sparsity: {sparsity:.2f}%")

    # Plot gate distribution
    plt.hist(gates, bins=50)
    plt.title(f"Gate Distribution (Lambda={lam})")
    plt.xlabel("Gate Value")
    plt.ylabel("Frequency")
    plt.show()

print("\nFinal Results:")
print("Lambda | Accuracy | Sparsity")

for r in results:
    print(f"{r[0]} | {r[1]:.2f}% | {r[2]:.2f}%")